import Head from "next/head";
import { Button, Typography } from "@material-ui/core";
import MenuBook from "@material-ui/icons/MenuBook";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography gutterBottom>Home Page</Typography>
      <Link as="a" href="/blog">
        <Button variant="contained" color="primary" startIcon={<MenuBook />}>
          View My Blog
        </Button>
      </Link>
    </>
  );
}
